name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@asimovbio'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          corepack enable
          yarn set version stable
          yarn
          yarn version ${GITHUB_REF##*/}
      - name: Test (jest)
        run: yarn test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          add: 'package.json'
          push: true
